### ISSUE TITLE
Pulsar does not deal with prelinking

### ISSUE THREAD

**Issue by cedwards** [HubbleStack/Pulsar#6]
We need to update the Pulsar beacon to support prelinking on CentOS 6 systems. Ideally this is turned off before deploying Pulsar (optional), but otherwise we need to un-prelink the file before we gather the checksum and stat information. Basic example:

<event>
<un-prelink file>
<checksum & stat>
<re-prelink file>
<return>

There is not a prelink Salt module, but we could use `cmd.run` with `prelink -u filename`

**Comment by basepi** [comment]
Will this be acceptable for the teams involved? If they don't want to disable prelinking will they be ok with us doing it automatically like this?

**Comment by basepi** [comment]
After talking with the teams involved (specifically Analytics today), it looks like unlinking files before calculating checksums is a non-starter. It could have performance impacts. So instead we're just going to rely on change notifications to spot problems in those cases, rather than the checksums themselves.
